routes/web.php
    Route::get('level', 'EducationController@educationLevel')->name('level');
    Route::get('not-attending-reason', 'EducationController@reason')->name('school.not.attending.reasons');
    Route::get('school-attend', 'EducationController@attend')->name('school.attending');
    Route::get('skill', 'EducationController@skill')->name('skills');
    Route::get('training', 'EducationController@training')->name('training');
});

//Health
Route::prefix('health')->name('health.')->group(function () {
    Route::get('life-long-disease', 'HealthController@lifelong')->name('life.long.disease');
    Route::get('vaccination', 'HealthController@vaccination')->name('vaccination');
    Route::get('safe-delivery', 'HealthController@safe')->name('safe');
    Route::get('birth', 'HealthController@birth')->name('birth');
    Route::get('total-birth', 'HealthController@totalBirth')->name('total.birth');
    Route::get('child-weight', 'HealthController@childWeight')->name('child.weight');
    Route::get('delivery-place', 'HealthController@delivery')->name('delivery.place');
    Route::get('mother-age', 'HealthController@motherAge')->name('mother.age');
    Route::get('emergency-disease', 'HealthController@emergency')->name('emergency.disease');
});

//Absentees
Route::prefix('absentees')->name('absentees.')->group(function () {
    Route::get('gender', 'AbsenteesController@gender')->name('gender');
    Route::get('agewise', 'AbsenteesController@agewise')->name('agewise');
    Route::get('education', 'AbsenteesController@education')->name('education');
    Route::get('reason', 'AbsenteesController@reason')->name('reasons');
    Route::get('currently-staying', 'AbsenteesController@current')->name('currently.stayiing');
});

Route::get('communityBuilding', 'InstitutionalController@communityBuilding');
Route::get('communityForest', 'InstitutionalController@communityForest');
Route::get('publicToilets', 'InstitutionalController@publicToilets');
Route::get('waterLands', 'InstitutionalController@waterLands');
Route::get('irrigation', 'InstitutionalController@irrigation');
Route::get('agroFarms', 'InstitutionalController@agroFarms');
Route::get('agroGroups', 'InstitutionalController@agroGroups');
Route::get('tourisms', 'InstitutionalController@tourisms');
Route::get('religious', 'InstitutionalController@religious');
Route::get('agroPocket', 'InstitutionalController@agroPocket');
Route::get('roads', 'InstitutionalController@roads');
Route::get('bridge', 'InstitutionalController@bridge');
Route::get('drinkingWater', 'InstitutionalController@drinkingWater');
Route::get('haatBazar', 'InstitutionalController@haatBazar');
Route::get('tlo', 'InstitutionalController@tlo');
Route::get('cooperatives', 'InstitutionalController@cooperatives');
Route::get('banks', 'InstitutionalController@banks');
Route::get('healthInstitutions', 'InstitutionalController@healthInstitutions');
Route::get('playground', 'InstitutionalController@playground');
Route::get('school', 'InstitutionalController@school');
Route::get('childrenClubs', 'InstitutionalController@childrenClubs');
Route::get('youthClubs', 'InstitutionalController@communityForest');
Route::get('publicPlaces', 'InstitutionalController@publicPlaces');
Route::get('crematorioum', 'InstitutionalController@crematorioum');
Route::get('womensGroup', 'InstitutionalController@womensGroup');
Route::get('socialHome', 'InstitutionalController@socialHome');
Route::get('colleges', 'InstitutionalController@colleges');



//Admin Area
Route::group(['middleware' => ['auth']], function () {

    Route::get('/admin/home', 'HomeController@index');
    Route::post('household/search', ['as' => 'search-house', 'uses' => 'HomeController@search']);

    Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {

        Route::get('/insertuser', 'UserController@createuser');
        Route::post('/storeuser', 'UserController@storeuser');
        Route::get('/userdeleteform/{id}', 'UserController@deleteuser');
        Route::get('/viewuser', 'UserController@viewuser');
        Route::get('/changePassword/{id}', 'UserController@showChangePasswordForm');
        Route::put('/changePassworduser/{id}', 'UserController@changePassworduser')->name('changePassworduser');

        Route::get('school', 'SchoolController@index');

        //Family
        // Route::resource('housing_household', 'HousingHouseholdController');

        Route::get('housing_household', 'HousingHouseholdController@index');
        Route::post('housing_household', 'HousingHouseholdController@update');

        Route::get('PersonalInof', 'PersonalInformationController@index');
        Route::post('PersonalInof', 'PersonalInformationController@update');

        Route::resource('IndividualInfo', 'GeneralindividualinformationController');

        Route::get('cover', 'GeneralindividualinformationController@index');
        Route::get('cover_create', 'GeneralindividualinformationController@create');
        Route::get('search', 'GeneralindividualinformationController@getData');

        // Route::get('details', 'viewdetailsController@getDetails');
        Route::resource('details', 'viewdetailsController');

        //College
        Route::resource('college', 'CollegeController');

        //ChildrenClub
        Route::resource('children-club', 'ChildrenClubController');

        //SocialHome
        Route::resource('social-home', 'SocialHomeController');

        //WomenGroup
        Route::resource('women-group', 'WomenGroupController');

        //AgroFarm
        Route::resource('agro-farm', 'AgroFarmController');

        //AgroVet
        Route::resource('agro-vet', 'AgroVetController');

        //Agro Vet pocket
        Route::resource('agro-vet-pocket', 'AgroVetPocketController');

        //PublicPlace
        Route::resource('public-place', 'PublicPlaceController');

        //Playground
        Route::resource('playground', 'PlaygroundController');

        //Club
        Route::resource('youth-club', 'ClubController');

        //CommunityBuildings
        Route::resource('community-building', 'CommunityBuildingController');

        Route::resource('drinking-water', 'DrinkWaterProjectController');

        //Bank
        Route::resource('bank', 'BankController');
        Route::post('t/search', ['as' => 'search-bank', 'uses' => 'BankController@search']);

        //Religious
        Route::resource('religious', 'ReligiousController');

        //Tourism
        Route::resource('tourism', 'TourismController');

        //TLO
        Route::resource('tlo', 'TLOController');

        //Cooperative
        Route::resource('cooperative', 'CooperativeController');

        //HealthInstitution
        Route::resource('health-institution', 'HealthInstutionController');

        Route::get('school', 'SchoolController@index');

        //Public Toilet

        Route::resource('public-toilet', 'PublicToiletController');

        //Bridge
        Route::resource('bridge', 'BridgeController');

        //irrigation_projects
        Route::resource('irrigation', 'IrrigationController');

        //Haat Bazar
        Route::resource('haat-bazar', 'HaatBazarController');

        //Ponds Lakes Weland
        Route::resource('pond-lake-wetland', 'PondsLakesWetlandController');

        //Comunity Forest
        Route::resource('community-forest', 'CommunityForestController');

        //Road_Networks
        Route::resource('road-network', 'RoadNetworkController');

        //Drinking Water Route
        Route::resource('drinking-water-projects', 'DrinkWaterProjectController');

        //Crematorium
        Route::resource('crematorium', 'CrematoriumController');

        //Impoertantcontact.......
        Route::get('/insertcontact', 'ImportantContactController@createcontact');
        Route::post('/storecontact', 'ImportantContactController@storecontact');
        Route::get('/viewcontact', 'ImportantContactController@viewcontact');
        Route::get('/changecontactStatus/{id}', 'ImportantContactController@changeStatus');
        Route::get('/contactedit/{id}', 'ImportantContactController@editcontact');
        Route::put('/updatecontact/{id}', 'ImportantContactController@updatecontact');
        Route::delete('/contactdeleteform/{id}', 'ImportantContactController@deletecontact');

        //carousel.......
        Route::get('/insertcarousel', 'CarouselController@createcarousel');
        Route::post('/storecarousel', 'CarouselController@storecarousel');
        Route::get('/viewcarousel', 'CarouselController@viewcarousel');
        Route::get('/changecarouselStatus/{id}', 'CarouselController@changeStatus');
        Route::get('/carouseledit/{id}', 'CarouselController@editcarousel');
        Route::put('/updatecarousel/{id}', 'CarouselController@updatecarousel');
        Route::delete('/carouseldeleteform/{id}', 'CarouselController@deletecarousel');

        //logo.......
        Route::get('/insertlogo', 'LogoController@createlogo');
        Route::post('/storelogo', 'LogoController@storelogo');
        Route::get('/viewlogo', 'LogoController@viewlogo');
        Route::get('/changelogoStatus/{id}', 'LogoController@changeStatus');
        Route::get('/logoedit/{id}', 'LogoController@editlogo');
        Route::put('/updatelogo/{id}', 'LogoController@updatelogo');
        Route::delete('/logodeleteform/{id}', 'LogoController@deletelogo');

        //Description.......
        Route::get('/insertdescription', 'DescriptionController@createdescription');
        Route::post('/storedescription', 'DescriptionController@storedescription');
        Route::get('/viewdescription', 'DescriptionController@viewdescription');
        Route::get('/changedescriptionStatus/{id}', 'DescriptionController@changeStatus');
        Route::get('/descriptionedit/{id}', 'DescriptionController@editdescription');
        Route::put('/updatedescription/{id}', 'DescriptionController@updatedescription');

app/SocialHome.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class SocialHome extends Model
{
    public $timestamps = false;

    public static function getSocialHome($ward = null)
    {
        if (is_null($ward) || $ward < 1 || $ward > TOTAL_WARD || !is_numeric($ward)) {
            // return "Ward No : ".$ward;
            // return "True Playground";
            return self::all();
        } else {
            // return "Else Part of Playground";
            return self::where('ward', '=', $ward)->get();
        }
    }
}

app/Http/Controllers/Admin/SocialHomeController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\SocialHome;
use Illuminate\Http\Request;
use Validator;
use File;

class SocialHomeController extends Controller
{
    public function create()
    {
        return view('admin.SocialHome.social_homeAdd', ['data' => new SocialHome()]);
    }

    public function store(Request $request)
    {
        self::validatedData($request);
        $data = new SocialHome();
        if ($request->hasFile('photo')) {
            $file = $request->file('photo');
            $destinationpath = 'uploads/socialhome';
            $uploadedImageName = uniqid() . '_' . $file->getClientOriginalName(); // unique file name with extension
            $file->move($destinationpath, $uploadedImageName);
            $data->photo = $uploadedImageName;
        }
        $this->setDataValue($request, $data);

        $data->save();
        self::Socialjson();
        session()->flash('status', 'insert');
        return redirect('admin/social-home');
    }

    public function index()
    {
        $data = SocialHome::paginate(10);
        return view('admin.SocialHome.social_home_show')->with('socialhome', $data);
    }

    public function edit($id)
    {
        $data = SocialHome::findOrFail($id);
        return view('admin.SocialHome.social_homeAdd')->with('data', $data);
    }

    public function update(Request $request, $id)
    {
        self::validatedData($request);
        $data = SocialHome::findOrFail($id);
        $this->setDataValue($request, $data);
        if ($request->hasFile('photo')) {

            $data_image = SocialHome::findOrFail($id);
            if ($data_image->photo && file_exists("uploads/socialhome/{$data_image->photo}")) {
                unlink("uploads/socialhome/{$data_image->photo}");
            }
            $file =  $request->file('photo');
            $destinationpath = 'uploads/socialhome';
            $uploadedImageName = uniqid() . '_' . $file->getClientOriginalName(); // unique file name with extension
            $file->move($destinationpath, $uploadedImageName);
            $data->photo = $uploadedImageName;
        }
        // dd($data);
        $data->update();
        self::Socialjson();
        session()->flash('status', 'success');
        return redirect('admin/social-home');
    }

    public function destroy($id)
    {

        $del = SocialHome::findOrFail($id);
        if ($del->photo && file_exists("uploads/socialhome/{$del->photo}")) {
            unlink("uploads/socialhome/{$del->photo}");
        }
        $data = SocialHome::findOrFail($id);
        $data->delete();
        self::Socialjson();
        session()->flash('status', 'delet');

        return redirect('admin/social-home');
    }
    protected function setDataValue($request, $data)
    {
        return array(
            $data->name = $request->input('name'),
            $data->ward = $request->input('ward'),
            $data->type = $request->input('type'),
            $data->address = $request->input('address'),
            $data->contact_person = $request->input('contact_person'),
            $data->contact_number = $request->input('contact_no'),
            $data->latitude = $request->input('latitude'),
            $data->remarks = $request->input('remarks'),
            $data->longitude = $request->input('longitude')
        );
    }

    protected function validatedData(Request $request)
    {
        $rules = [
            'name' => 'required',
            'ward' => 'nullable',
            'address' => 'nullable',
            'type' => 'nullable',
            'contact_person' => 'nullable',
            'latitude' => 'nullable|numeric',
            'longitude' => 'nullable|numeric',
            'photo.*' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'remarks' => 'nullable',
            'contact_no' => 'nullable',
        ];

        $customMessages = [
            'name.required' => 'गृह / केन्द्रको नाम क्षेत्र आवश्यक छ।',
            'address.required' => 'ठेगाना क्षेत्र आवश्यक छ।',
            'latitude.required' => 'अक्षांश क्षेत्र आवश्यक छ।',
            'longitude.required' => 'देशान्तर क्षेत्र आवश्यक छ।',
            'ward.required' => 'वडा क्षेत्र आवश्यक छ।',
            'type.required' => 'प्रकार क्षेत्र आवश्यक छ।',
            'contact_person.required' => 'सम्पर्क वयक्ति क्षेत्र आवश्यक छ।',
            'photo.required' => 'फोटो क्षेत्र आवश्यक छ।',
            'remarks.required' => 'कैफियत प्रकार क्षेत्र आवश्यक छ।',
            'contact_no.required' => 'सम्पर्क नं क्षेत्र आवश्यक छ।',
        ];

        $this->validate($request, $rules, $customMessages);
    }
    public function Socialjson()
    {
        $social = SocialHome::all();
        $socialdata = json_encode($social,JSON_UNESCAPED_UNICODE);
        $file = 'socialhomedetails' . '_file.json';
        $destinationPath = public_path() . "/upload/json/";
        if (!is_dir($destinationPath)) {
            mkdir($destinationPath, 0777, true);
        }
        File::put($destinationPath . $file, $socialdata);
    }
}

resources/views/admin/SocialHome/social_home_show.blade.php
@extends('template.admin')
@section('title', 'महिला सुरक्षा गृह/ बाल गृह/ बाल स्याहार केन्द्र /विद्धाश्राम वा सत्सङ्ग केन्द्र')
@section('page-title')
    महिला सुरक्षा गृह/ बाल गृह/ बाल स्याहार केन्द्र /विद्धाश्राम वा सत्सङ्ग केन्द्र
@endsection
@section('content')
    <div class="content-wrapper">


        @if (session('status') == 'success')
            <button class="btn btn-success mt-sweetalert gk-btn-success" id="gk-success" data-title="Updated"
                data-message="Member Updated Succesfuly" data-type="success" data-allow-outside-click="true"
                data-confirm-button-class="btn-success"></button>
        @elseif (session('status') == 'delet')
            <button class="btn btn-danger mt-sweetalert gk-btn-success" id="gk-success" data-title="मेटाइयो"
                data-message="सार्वजनिक शौचालय मेटाइयो" data-type="error" data-allow-outside-click="true"
                data-confirm-button-class="btn-danger"></button>
        @elseif (session('status') == 'insert')
            <button class="btn btn-success mt-sweetalert gk-btn-success" id="gk-success" data-title="Inserted"
                data-message="Member Insert Succesfuly" data-type="success" data-allow-outside-click="true"
                data-confirm-button-class="btn-success"></button>

        @endif

        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="{{ url('admin/home') }}">Dashboard</a>
                    <i class="far fa-circle"></i>
                </li>

                <li>
                    <span>महिला सुरक्षा गृह/ बाल गृह/ बाल स्याहार केन्द्र /विद्धाश्राम वा सत्सङ्ग केन्द्र </span>
                </li>
            </ul>

        </div>
        <section class="content">

            <div class="row">
                <div class="col-md-12">
                    <!-- BEGIN EXAMPLE TABLE PORTLET-->
                    <div class="portlet light bordered">
                        <div class="portlet-title">
                            <div class="caption font-dark">
                                <i class="icon-settings font-dark"></i>


                                <span class="caption-subject bold uppercase"> महिला सुरक्षा गृह/ बाल गृह/ बाल स्याहार
                                    केन्द्र /विद्धाश्राम वा सत्सङ्ग केन्द्र</span>
                            </div>

                        </div>
                        <div class="portlet-body">
                            <div class="table-toolbar">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="btn-group">
                                            <a id="sample_editable_1_new" class="btn sbold green"
                                                href="{{ route('admin.social-home.create') }}"> नयाँ जोड्नुहोस्
                                                <i class="fa fa-plus"></i>
                                            </a>
                                        </div>
                                    </div>

                                </div>
                            </div>

                            <table class="table table-bordered table-striped table-condensed flip-content">
                                <thead class="flip-content">
                                    <tr>

                                        <th>गृह / केन्द्रको नाम</th>
                                        <th>वडा</th>
                                        <th>ठेगाना</th>
                                        <th>प्रकार</th>
                                        <th>सम्पर्क वयक्ति</th>
                                        <th>सम्पर्क नं.</th>
                                        <th>Edit</th>
                                        <th>Delete</th>

                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach ($socialhome as $data)
                                        <tr>

                                            <td>{{ $data->name }}</td>
                                            <td>{{ $data->ward }}</td>
                                            <td>{{ $data->address }}</td>
                                            <td>{{ $data->type }}</td>
                                            <td>{{ $data->contact_person }}</td>
                                            <td>{{ $data->contact_number }}</td>
                                            <td>

                                                <a href="{{ route('admin.social-home.edit', $data->id) }}"
                                                    class="btn btn-circle green"> सम्पादन गर्नुहोस्
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                            </td>


                                            <td><a href="#" data-toggle="modal" data-target="#{{ $data->id }}"
                                                    class="btn btn-circle red"><i class="fa fa-remove"></i>मेटाउन</a>

                                                </a>
                                                <div id="{{ $data->id }}" class="modal fade" tabindex="-1"
                                                    data-backdrop="static" data-keyboard="false">
                                                    <div class="___class_+?38___">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <button type="button" class="close"
                                                                    data-dismiss="modal" aria-hidden="true"></button>
                                                                <h4 class="modal-title">पुष्टिकरण</h4>
                                                            </div>
                                                            <div class="modal-body">
                                                                <p> के तपाइँ यसलाई {{ $data->name }} मेटाउन चाहानुहुन्छ?
                                                                </p>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" data-dismiss="modal"
                                                                    class="btn dark btn-outline">रद्द गर्नुहोस्</button>


                                                                <form class="form-sample" method="POST"
                                                                    action="{{ Route('admin.social-home.destroy', $data->id) }}">

                                                                    @csrf
                                                                    @method('DELETE')
                                                                    <button type="submit" class="btn green">हो</button>
                                                                </form>



                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>


                                    @endforeach





                                </tbody>
                                {{-- <tfoot>
                          <th>Total</th>
                          <th>{{$totalMale}}</th>
                            <th>{{$totalFemale}}</th>
                            <th>{{$totalOther}}</th>
                            <th>{{$totalMale + $totalFemale + $totalOther}}</th>
                            </tfoot> --}}
                            </table>
                            {{ $socialhome->links() }}
                            {{-- end of table --}}
                        </div> {{-- end of .table-responsive --}}
                    </div>
                </div>
            </div>

        </section>
    </div>







    <!-- /.example-modal -->

@endsection
{{-- end main-content section --}}