routes/web.php
    Route::get('disability', 'PersonController@disability')->name('disability');
    Route::get('marital-status', 'PersonController@maritalStatus');
    Route::get('marital-status-current-age', 'PersonController@ageAtFirstMarriage')->name('marital.status.current.age');
    Route::get('marital-status', 'PersonController@maritalStatus')->name('marital.status');
    Route::get('age-at-first-marriage', 'PersonController@ageAtFirstMarriage')->name('first.marriage.age');
    Route::get('literacy', 'PersonController@literacy')->name('literacy');
    Route::get('birthplace', 'PersonController@birthplace')->name('birth.place');
});

//Education
Route::prefix('education')->name('education.')->group(function () {
    Route::get('literacy', 'PersonController@literacy')->name('literacy');
    Route::get('level', 'EducationController@educationLevel')->name('level');
    Route::get('not-attending-reason', 'EducationController@reason')->name('school.not.attending.reasons');
    Route::get('school-attend', 'EducationController@attend')->name('school.attending');
    Route::get('skill', 'EducationController@skill')->name('skills');
    Route::get('training', 'EducationController@training')->name('training');
});

//Health
Route::prefix('health')->name('health.')->group(function () {
    Route::get('life-long-disease', 'HealthController@lifelong')->name('life.long.disease');
    Route::get('vaccination', 'HealthController@vaccination')->name('vaccination');
    Route::get('safe-delivery', 'HealthController@safe')->name('safe');
    Route::get('birth', 'HealthController@birth')->name('birth');
    Route::get('total-birth', 'HealthController@totalBirth')->name('total.birth');
    Route::get('child-weight', 'HealthController@childWeight')->name('child.weight');
    Route::get('delivery-place', 'HealthController@delivery')->name('delivery.place');
    Route::get('mother-age', 'HealthController@motherAge')->name('mother.age');
    Route::get('emergency-disease', 'HealthController@emergency')->name('emergency.disease');
});

//Absentees
Route::prefix('absentees')->name('absentees.')->group(function () {
    Route::get('gender', 'AbsenteesController@gender')->name('gender');
    Route::get('agewise', 'AbsenteesController@agewise')->name('agewise');
    Route::get('education', 'AbsenteesController@education')->name('education');
    Route::get('reason', 'AbsenteesController@reason')->name('reasons');
    Route::get('currently-staying', 'AbsenteesController@current')->name('currently.stayiing');
});

Route::get('communityBuilding', 'InstitutionalController@communityBuilding');
Route::get('communityForest', 'InstitutionalController@communityForest');
Route::get('publicToilets', 'InstitutionalController@publicToilets');
Route::get('waterLands', 'InstitutionalController@waterLands');
Route::get('irrigation', 'InstitutionalController@irrigation');
Route::get('agroFarms', 'InstitutionalController@agroFarms');
Route::get('agroGroups', 'InstitutionalController@agroGroups');
Route::get('tourisms', 'InstitutionalController@tourisms');
Route::get('religious', 'InstitutionalController@religious');
Route::get('agroPocket', 'InstitutionalController@agroPocket');
Route::get('roads', 'InstitutionalController@roads');
Route::get('bridge', 'InstitutionalController@bridge');
Route::get('drinkingWater', 'InstitutionalController@drinkingWater');
Route::get('haatBazar', 'InstitutionalController@haatBazar');
Route::get('tlo', 'InstitutionalController@tlo');
Route::get('cooperatives', 'InstitutionalController@cooperatives');
Route::get('banks', 'InstitutionalController@banks');
Route::get('healthInstitutions', 'InstitutionalController@healthInstitutions');
Route::get('playground', 'InstitutionalController@playground');
Route::get('school', 'InstitutionalController@school');
Route::get('childrenClubs', 'InstitutionalController@childrenClubs');
Route::get('youthClubs', 'InstitutionalController@communityForest');
Route::get('publicPlaces', 'InstitutionalController@publicPlaces');
Route::get('crematorioum', 'InstitutionalController@crematorioum');
Route::get('womensGroup', 'InstitutionalController@womensGroup');
Route::get('socialHome', 'InstitutionalController@socialHome');
Route::get('colleges', 'InstitutionalController@colleges');



//Admin Area
Route::group(['middleware' => ['auth']], function () {

    Route::get('/admin/home', 'HomeController@index');
    Route::post('household/search', ['as' => 'search-house', 'uses' => 'HomeController@search']);

    Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {

        Route::get('/insertuser', 'UserController@createuser');
        Route::post('/storeuser', 'UserController@storeuser');
        Route::get('/userdeleteform/{id}', 'UserController@deleteuser');
        Route::get('/viewuser', 'UserController@viewuser');
        Route::get('/changePassword/{id}', 'UserController@showChangePasswordForm');
        Route::put('/changePassworduser/{id}', 'UserController@changePassworduser')->name('changePassworduser');

        Route::get('school', 'SchoolController@index');

        //Family
        // Route::resource('housing_household', 'HousingHouseholdController');

        Route::get('housing_household', 'HousingHouseholdController@index');
        Route::post('housing_household', 'HousingHouseholdController@update');

        Route::get('PersonalInof', 'PersonalInformationController@index');
        Route::post('PersonalInof', 'PersonalInformationController@update');

        Route::resource('IndividualInfo', 'GeneralindividualinformationController');

        Route::get('cover', 'GeneralindividualinformationController@index');
        Route::get('cover_create', 'GeneralindividualinformationController@create');
        Route::get('search', 'GeneralindividualinformationController@getData');

        // Route::get('details', 'viewdetailsController@getDetails');
        Route::resource('details', 'viewdetailsController');

        //College
        Route::resource('college', 'CollegeController');

        //ChildrenClub
        Route::resource('children-club', 'ChildrenClubController');

        //SocialHome
        Route::resource('social-home', 'SocialHomeController');

        //WomenGroup
        Route::resource('women-group', 'WomenGroupController');

        //AgroFarm
        Route::resource('agro-farm', 'AgroFarmController');

        //AgroVet
        Route::resource('agro-vet', 'AgroVetController');

        //Agro Vet pocket
        Route::resource('agro-vet-pocket', 'AgroVetPocketController');

        //PublicPlace
        Route::resource('public-place', 'PublicPlaceController');

        //Playground
        Route::resource('playground', 'PlaygroundController');

        //Club
        Route::resource('youth-club', 'ClubController');

        //CommunityBuildings
        Route::resource('community-building', 'CommunityBuildingController');

        Route::resource('drinking-water', 'DrinkWaterProjectController');

        //Bank
        Route::resource('bank', 'BankController');
        Route::post('t/search', ['as' => 'search-bank', 'uses' => 'BankController@search']);

        //Religious
        Route::resource('religious', 'ReligiousController');

        //Tourism
        Route::resource('tourism', 'TourismController');

        //TLO
        Route::resource('tlo', 'TLOController');

        //Cooperative
        Route::resource('cooperative', 'CooperativeController');

        //HealthInstitution
        Route::resource('health-institution', 'HealthInstutionController');

        Route::get('school', 'SchoolController@index');

        //Public Toilet

        Route::resource('public-toilet', 'PublicToiletController');

        //Bridge
        Route::resource('bridge', 'BridgeController');

        //irrigation_projects
        Route::resource('irrigation', 'IrrigationController');

        //Haat Bazar
        Route::resource('haat-bazar', 'HaatBazarController');

        //Ponds Lakes Weland
        Route::resource('pond-lake-wetland', 'PondsLakesWetlandController');

        //Comunity Forest
        Route::resource('community-forest', 'CommunityForestController');

        //Road_Networks
        Route::resource('road-network', 'RoadNetworkController');

        //Drinking Water Route
        Route::resource('drinking-water-projects', 'DrinkWaterProjectController');

        //Crematorium
        Route::resource('crematorium', 'CrematoriumController');

        //Impoertantcontact.......
        Route::get('/insertcontact', 'ImportantContactController@createcontact');
        Route::post('/storecontact', 'ImportantContactController@storecontact');
        Route::get('/viewcontact', 'ImportantContactController@viewcontact');
        Route::get('/changecontactStatus/{id}', 'ImportantContactController@changeStatus');
        Route::get('/contactedit/{id}', 'ImportantContactController@editcontact');
        Route::put('/updatecontact/{id}', 'ImportantContactController@updatecontact');
        Route::delete('/contactdeleteform/{id}', 'ImportantContactController@deletecontact');

        //carousel.......
        Route::get('/insertcarousel', 'CarouselController@createcarousel');
        Route::post('/storecarousel', 'CarouselController@storecarousel');
        Route::get('/viewcarousel', 'CarouselController@viewcarousel');
        Route::get('/changecarouselStatus/{id}', 'CarouselController@changeStatus');
        Route::get('/carouseledit/{id}', 'CarouselController@editcarousel');
        Route::put('/updatecarousel/{id}', 'CarouselController@updatecarousel');
        Route::delete('/carouseldeleteform/{id}', 'CarouselController@deletecarousel');

        //logo.......
        Route::get('/insertlogo', 'LogoController@createlogo');
        Route::post('/storelogo', 'LogoController@storelogo');
        Route::get('/viewlogo', 'LogoController@viewlogo');
        Route::get('/changelogoStatus/{id}', 'LogoController@changeStatus');

app/HaatBazar.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class HaatBazar extends Model
{
    
    public $timestamps = false;
    public static function getHaatBazar($ward=null){
        if(is_null($ward) || $ward<1 || $ward>TOTAL_WARD || !is_numeric($ward)){            
            return self::orderBy('ward')->get();
        }else{            
            return self::where('ward','=',$ward)->get();
        }
    }
}

app/Http/Controllers/Admin/HaatBazarController.php
<?php

namespace App\Http\Controllers\Admin;

use App\HaatBazar;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;
use DB;
use File;


class HaatBazarController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        // if (file_exists("upload/json/haatbazar_file.json")) {
        //     $data = json_decode(file_get_contents("upload/json/haatbazar_file.json"));
        //     return view('haat_bazar.haat_bazar_details')->with('data', $data);
        // } else
            $data = HaatBazar::paginate(10);
        return view('haat_bazar.haat_bazar_details')->with('haatbazar', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('haat_bazar.haat_bazar', ['data' => new HaatBazar()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        self::validatedData($request);
        $data = new HaatBazar();
        if ($request->hasFile('photo')) {
            $file = $request->file('photo');
            $destinationpath = 'uploads/haatbazar';
            $uploadedImageName = uniqid() . '_' . $file->getClientOriginalName(); // unique file name with extension
            $file->move($destinationpath, $uploadedImageName);
            $data->photo = $uploadedImageName;
        }
        $this->setDataValue($request, $data);
        $data->save();
        self::Haatbazarjson();
        session()->flash('status', 'insert');
        return redirect('admin/haat-bazar');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

    public function edit($id)
    {
        $data = HaatBazar::find($id);
        if (!$data) {
            $request->session()->flash('msg', 'Record not found !');
            return redirect('admin/haat-bazar');
        }
        return view('haat_bazar.haat_bazar', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        self::validatedData($request);

        $data = HaatBazar::findOrFail($id);
        $this->setDataValue($request, $data);
        if ($request->hasFile('photo')) {

            $data_image = HaatBazar::findOrFail($id);
            if ($data_image->photo && file_exists("uploads/haatbazar/{$data_image->photo}")) {
                unlink("uploads/haatbazar/{$data_image->photo}");
            }
            $file =  $request->file('photo');
            $destinationpath = 'uploads/haatbazar';
            $uploadedImageName = uniqid() . '_' . $file->getClientOriginalName(); // unique file name with extension
            $file->move($destinationpath, $uploadedImageName);
            $data->photo = $uploadedImageName;
        }

        self::Haatbazarjson();
        $data->update();
        session()->flash('status', 'success');
        return redirect('admin/haat-bazar');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id, Request $request)
    {
        $del = HaatBazar::findOrFail($id);
        if ($del->photo && file_exists("uploads/haatbazar/{$del->photo}")) {
            unlink("uploads/haatbazar/{$del->photo}");
        }
        $data = HaatBazar::findOrFail($id);
        $data->delete();
        self::Haatbazarjson();
        session()->flash('status', 'delet');
        return redirect('admin/haat-bazar');
    }
    protected function setDataValue($request, $data)
    {
        return array(
            $data->name = $request->input('name'),
            $data->ward = $request->input('ward'),
            $data->address = $request->input('address'),
            $data->type = $request->input('type'),
            $data->day = $request->input('day'),
            $data->interval = $request->input('interval'),
            $data->infrastructure = $request->input('infrastructure'),
            $data->remarks = $request->input('remarks'),
            $data->latitude = $request->input('latitude'),
            $data->longitude = $request->input('longitude')


        );
    }
    protected function validatedData(Request $request)


    {
        $rules = [
            'name' => 'required',
            'ward' => 'required',
            'address' => 'nullable',
            'infrastructure' => 'nullable',
            'day' => 'nullable',
            'type' => 'nullable',
            'interval' => 'nullable',
            'latitude' => 'nullable|numeric',
            'longitude' => 'nullable|numeric',
            'photo.*' => 'nullable|image|mimes:jpeg,png,jpg,gif,svg|max:2048',
            'remarks' => 'nullable',
        ];
        $customMessages = [
            'name.required' => 'हाट बजारस्थलको क्षेत्र आवश्यक छ।',
            'address.required' => 'ठेगाना क्षेत्र आवश्यक छ।',
            'latitude.required' => 'अक्षांश क्षेत्र आवश्यक छ।',
            'longitude.required' => 'देशान्तर क्षेत्र आवश्यक छ।',
            'ward.required' => 'वडा क्षेत्र आवश्यक छ।',
            'infrastructure.required' => 'उपलब्ध प्रमुख पूर्वाधार क्षेत्र आवश्यक छ।',
            'type.required' => 'प्रकार क्षेत्र आवश्यक छ।',
            'day.required' => 'हाट बजार लाग्ने दिन क्षेत्र आवश्यक छ।',
            'photo.required' => 'फोटो क्षेत्र आवश्यक छ।',
            'remarks.required' => 'कैफियत प्रकार क्षेत्र आवश्यक छ।',
            'interval.required' => 'हाट लाग्ने अन्तराल क्षेत्र आवश्यक छ।',
        ];
        $this->validate($request, $rules, $customMessages);
    }

    public function Haatbazarjson()
    {
        $haat = HaatBazar::all();
        $haatdata = json_encode($haat,JSON_UNESCAPED_UNICODE);
        $file = 'haatbazar' . '_file.json';
        $destinationPath = public_path() . "/upload/json/";
        if (!is_dir($destinationPath)) {
            mkdir($destinationPath, 0777, true);
        }
        File::put($destinationPath . $file, $haatdata);
    }
}

resources/views/haat_bazar/haat_bazar_details.blade.php
@extends('template.admin')
@section('title', 'कृषि तथा हाट बजार सम्बन्धी विवरण')
@section('page-title')
    कृषि तथा हाट बजार सम्बन्धी विवरण
@endsection
@section('content')
    <div class="content-wrapper">


        @if (session('status') == 'success')
            <button class="btn btn-success mt-sweetalert gk-btn-success" id="gk-success" data-title="Updated"
                data-message="Member Updated Succesfuly" data-type="success" data-allow-outside-click="true"
                data-confirm-button-class="btn-success"></button>
        @elseif (session('status') == 'delet')
            <button class="btn btn-danger mt-sweetalert gk-btn-success" id="gk-success" data-title="मेटाइयो"
                data-message="सार्वजनिक शौचालय मेटाइयो" data-type="error" data-allow-outside-click="true"
                data-confirm-button-class="btn-danger"></button>
        @elseif (session('status') == 'insert')
            <button class="btn btn-success mt-sweetalert gk-btn-success" id="gk-success" data-title="Inserted"
                data-message="Member Insert Succesfuly" data-type="success" data-allow-outside-click="true"
                data-confirm-button-class="btn-success"></button>

        @endif

        <div class="page-bar">
            <ul class="page-breadcrumb">
                <li>
                    <a href="{{ url('admin/home') }}">Dashboard</a>
                    <i class="fa fa-circle"></i>
                </li>

                <li>
                    <span>कृषि तथा हाट बजार सम्बन्धी विवरण </span>
                </li>
            </ul>
            <div class="page-toolbar">
                <div id="dashboard-report-range" class="pull-right tooltips btn btn-sm" data-container="body"
                    data-placement="bottom" data-original-title="Change dashboard date range">
                    <i class="icon-calendar"></i>&nbsp;
                    <span class="thin uppercase hidden-xs"></span>&nbsp;
                    <i class="fa fa-angle-down"></i>
                </div>
            </div>
        </div>
        <section class="content">

            <div class="row">
                <div class="col-md-12">
                    <!-- BEGIN EXAMPLE TABLE PORTLET-->
                    <div class="portlet light bordered">
                        <div class="portlet-title">
                            <div class="caption font-dark">
                                <i class="icon-settings font-dark"></i>
                                <span class="caption-subject bold uppercase"> कृषि तथा हाट बजार सम्बन्धी विवरण</span>
                            </div>

                        </div>
                        <div class="portlet-body">
                            <div class="table-toolbar">
                                <div class="row">
                                    <div class="col-md-6">
                                        <div class="btn-group">
                                            <a id="sample_editable_1_new" class="btn sbold green"
                                                href="{{ route('admin.haat-bazar.create') }}"> नयाँ जोड्नुहोस्
                                                <i class="fa fa-plus"></i>
                                            </a>
                                        </div>
                                    </div>

                                </div>
                            </div>

                            <table class="table table-bordered table-striped table-condensed flip-content">
                                <thead class="flip-content">
                                    <tr>

                                        <th>हाट बजारस्थलको नाम</th>
                                        <th>वडा</th>
                                        <th>ठेगाना</th>
                                        <th>हाट बजार लाग्ने दिन</th>
                                        <th>हाट लाग्ने अनतराल</th>
                                        <th>उपलब्ध प्रमुख पूर्वाधार</th>
                                        <th>कैफियत</th>
                                        <th>Edit</th>
                                        <th>Delete</th>

                                    </tr>
                                </thead>
                                <tbody>

                                    @foreach ($haatbazar as $data)
                                        <tr>

                                            <td>{{ $data->name }}</td>
                                            <td>{{ $data->ward }}</td>
                                            <td>{{ $data->address }}</td>
                                            <td>{{ $data->day }}</td>
                                            <td>{{ $data->interval }}</td>
                                            <td>{{ $data->infrastructure }}</td>
                                            <td>{!! $data->remarks !!}</td>
                                            <td>

                                                <a href="{{ route('admin.haat-bazar.edit', $data->id) }}"
                                                    class="btn btn-circle green"> सम्पादन गर्नुहोस्
                                                    <i class="fa fa-edit"></i>
                                                </a>
                                            </td>


                                            <td><a href="#" data-toggle="modal" data-target="#{{ $data->id }}"
                                                    class="btn btn-circle red"><i class="fa fa-remove"></i>मेटाउन</a>

                                                </a>
                                                <div id="{{ $data->id }}" class="modal fade" tabindex="-1"
                                                    data-backdrop="static" data-keyboard="false">
                                                    <div class="___class_+?38___">
                                                        <div class="modal-content">
                                                            <div class="modal-header">
                                                                <button type="button" class="close"
                                                                    data-dismiss="modal" aria-hidden="true"></button>
                                                                <h4 class="modal-title">पुष्टिकरण</h4>
                                                            </div>
                                                            <div class="modal-body">
                                                                <p> के तपाइँ यसलाई {{ $data->name }} मेटाउन चाहानुहुन्छ?
                                                                </p>
                                                            </div>
                                                            <div class="modal-footer">
                                                                <button type="button" data-dismiss="modal"
                                                                    class="btn dark btn-outline">रद्द गर्नुहोस्</button>


                                                                <form class="form-sample" method="POST"
                                                                    action="{{ Route('admin.haat-bazar.destroy', $data->id) }}">

                                                                    @csrf
                                                                    @method('DELETE')
                                                                    <button type="submit" class="btn green">हो</button>
                                                                </form>



                                                            </div>
                                                        </div>
                                                    </div>
                                                </div>
                                            </td>


                                    @endforeach





                                </tbody>
                                {{-- <tfoot>
                          <th>Total</th>
                          <th>{{$totalMale}}</th>
                            <th>{{$totalFemale}}</th>
                            <th>{{$totalOther}}</th>
                            <th>{{$totalMale + $totalFemale + $totalOther}}</th>
                            </tfoot> --}}
                            </table>
                            {{ $haatbazar->links() }}
                            {{-- end of table --}}
                        </div> {{-- end of .table-responsive --}}
                    </div>
                </div>
            </div>

        </section>
    </div>







    <!-- /.example-modal -->

@endsection
{{-- end main-content section --}}