routes/web.php
//Population
Route::prefix('population')->name('population.')->group(function () {
    Route::get('gender', 'PersonController@genderwise')->name('gender');
    Route::get('gender/{ward}', 'PersonController@genderwise');
    Route::get('agewise', 'PersonController@agewise')->name('agewise');
    Route::get('religion', 'PersonController@religion')->name('religion');
    Route::get('caste', 'PersonController@caste')->name('caste');
    Route::get('motherTongue', 'PersonController@motherTongue')->name('mother.tongue');
    Route::get('disability', 'PersonController@disability')->name('disability');
    Route::get('marital-status', 'PersonController@maritalStatus');
    Route::get('marital-status-current-age', 'PersonController@ageAtFirstMarriage')->name('marital.status.current.age');
    Route::get('marital-status', 'PersonController@maritalStatus')->name('marital.status');
    Route::get('age-at-first-marriage', 'PersonController@ageAtFirstMarriage')->name('first.marriage.age');
    Route::get('literacy', 'PersonController@literacy')->name('literacy');
    Route::get('birthplace', 'PersonController@birthplace')->name('birth.place');
});

//Education
Route::prefix('education')->name('education.')->group(function () {
    Route::get('literacy', 'PersonController@literacy')->name('literacy');
    Route::get('level', 'EducationController@educationLevel')->name('level');
    Route::get('not-attending-reason', 'EducationController@reason')->name('school.not.attending.reasons');
    Route::get('school-attend', 'EducationController@attend')->name('school.attending');
    Route::get('skill', 'EducationController@skill')->name('skills');
    Route::get('training', 'EducationController@training')->name('training');
});

//Health
Route::prefix('health')->name('health.')->group(function () {
    Route::get('life-long-disease', 'HealthController@lifelong')->name('life.long.disease');
    Route::get('vaccination', 'HealthController@vaccination')->name('vaccination');
    Route::get('safe-delivery', 'HealthController@safe')->name('safe');
    Route::get('birth', 'HealthController@birth')->name('birth');
    Route::get('total-birth', 'HealthController@totalBirth')->name('total.birth');
    Route::get('child-weight', 'HealthController@childWeight')->name('child.weight');
    Route::get('delivery-place', 'HealthController@delivery')->name('delivery.place');
    Route::get('mother-age', 'HealthController@motherAge')->name('mother.age');
    Route::get('emergency-disease', 'HealthController@emergency')->name('emergency.disease');
});

//Absentees
Route::prefix('absentees')->name('absentees.')->group(function () {
    Route::get('gender', 'AbsenteesController@gender')->name('gender');
    Route::get('agewise', 'AbsenteesController@agewise')->name('agewise');
    Route::get('education', 'AbsenteesController@education')->name('education');
    Route::get('reason', 'AbsenteesController@reason')->name('reasons');
    Route::get('currently-staying', 'AbsenteesController@current')->name('currently.stayiing');
});

Route::get('communityBuilding', 'InstitutionalController@communityBuilding');
Route::get('communityForest', 'InstitutionalController@communityForest');
Route::get('publicToilets', 'InstitutionalController@publicToilets');
Route::get('waterLands', 'InstitutionalController@waterLands');
Route::get('irrigation', 'InstitutionalController@irrigation');
Route::get('agroFarms', 'InstitutionalController@agroFarms');
Route::get('agroGroups', 'InstitutionalController@agroGroups');
Route::get('tourisms', 'InstitutionalController@tourisms');
Route::get('religious', 'InstitutionalController@religious');
Route::get('agroPocket', 'InstitutionalController@agroPocket');
Route::get('roads', 'InstitutionalController@roads');
Route::get('bridge', 'InstitutionalController@bridge');
Route::get('drinkingWater', 'InstitutionalController@drinkingWater');
Route::get('haatBazar', 'InstitutionalController@haatBazar');
Route::get('tlo', 'InstitutionalController@tlo');
Route::get('cooperatives', 'InstitutionalController@cooperatives');
Route::get('banks', 'InstitutionalController@banks');
Route::get('healthInstitutions', 'InstitutionalController@healthInstitutions');
Route::get('playground', 'InstitutionalController@playground');
Route::get('school', 'InstitutionalController@school');
Route::get('childrenClubs', 'InstitutionalController@childrenClubs');
Route::get('youthClubs', 'InstitutionalController@communityForest');
Route::get('publicPlaces', 'InstitutionalController@publicPlaces');
Route::get('crematorioum', 'InstitutionalController@crematorioum');
Route::get('womensGroup', 'InstitutionalController@womensGroup');
Route::get('socialHome', 'InstitutionalController@socialHome');
Route::get('colleges', 'InstitutionalController@colleges');



//Admin Area
Route::group(['middleware' => ['auth']], function () {

    Route::get('/admin/home', 'HomeController@index');
    Route::post('household/search', ['as' => 'search-house', 'uses' => 'HomeController@search']);

    Route::namespace('Admin')->prefix('admin')->name('admin.')->group(function () {

        Route::get('/insertuser', 'UserController@createuser');
        Route::post('/storeuser', 'UserController@storeuser');
        Route::get('/userdeleteform/{id}', 'UserController@deleteuser');
        Route::get('/viewuser', 'UserController@viewuser');
        Route::get('/changePassword/{id}', 'UserController@showChangePasswordForm');
        Route::put('/changePassworduser/{id}', 'UserController@changePassworduser')->name('changePassworduser');

        Route::get('school', 'SchoolController@index');

        //Family
        // Route::resource('housing_household', 'HousingHouseholdController');

        Route::get('housing_household', 'HousingHouseholdController@index');
        Route::post('housing_household', 'HousingHouseholdController@update');

        Route::get('PersonalInof', 'PersonalInformationController@index');
        Route::post('PersonalInof', 'PersonalInformationController@update');

        Route::resource('IndividualInfo', 'GeneralindividualinformationController');

        Route::get('cover', 'GeneralindividualinformationController@index');
        Route::get('cover_create', 'GeneralindividualinformationController@create');
        Route::get('search', 'GeneralindividualinformationController@getData');

        // Route::get('details', 'viewdetailsController@getDetails');
        Route::resource('details', 'viewdetailsController');

        //College
        Route::resource('college', 'CollegeController');

        //ChildrenClub
        Route::resource('children-club', 'ChildrenClubController');

        //SocialHome
        Route::resource('social-home', 'SocialHomeController');

        //WomenGroup
        Route::resource('women-group', 'WomenGroupController');

        //AgroFarm
        Route::resource('agro-farm', 'AgroFarmController');

        //AgroVet
        Route::resource('agro-vet', 'AgroVetController');

        //Agro Vet pocket
        Route::resource('agro-vet-pocket', 'AgroVetPocketController');

        //PublicPlace
        Route::resource('public-place', 'PublicPlaceController');

        //Playground
        Route::resource('playground', 'PlaygroundController');

        //Club
        Route::resource('youth-club', 'ClubController');

        //CommunityBuildings
        Route::resource('community-building', 'CommunityBuildingController');

        Route::resource('drinking-water', 'DrinkWaterProjectController');

        //Bank
        Route::resource('bank', 'BankController');
        Route::post('t/search', ['as' => 'search-bank', 'uses' => 'BankController@search']);

        //Religious
        Route::resource('religious', 'ReligiousController');

        //Tourism
        Route::resource('tourism', 'TourismController');

        //TLO
        Route::resource('tlo', 'TLOController');

        //Cooperative
        Route::resource('cooperative', 'CooperativeController');

        //HealthInstitution
        Route::resource('health-institution', 'HealthInstutionController');

        Route::get('school', 'SchoolController@index');

        //Public Toilet

        Route::resource('public-toilet', 'PublicToiletController');

        //Bridge
        Route::resource('bridge', 'BridgeController');

        //irrigation_projects
        Route::resource('irrigation', 'IrrigationController');

        //Haat Bazar
        Route::resource('haat-bazar', 'HaatBazarController');

        //Ponds Lakes Weland
        Route::resource('pond-lake-wetland', 'PondsLakesWetlandController');

        //Comunity Forest
        Route::resource('community-forest', 'CommunityForestController');

        //Road_Networks
        Route::resource('road-network', 'RoadNetworkController');

        //Drinking Water Route
        Route::resource('drinking-water-projects', 'DrinkWaterProjectController');

        //Crematorium
        Route::resource('crematorium', 'CrematoriumController');

        //Impoertantcontact.......
        Route::get('/insertcontact', 'ImportantContactController@createcontact');
        Route::post('/storecontact', 'ImportantContactController@storecontact');
        Route::get('/viewcontact', 'ImportantContactController@viewcontact');
        Route::get('/changecontactStatus/{id}', 'ImportantContactController@changeStatus');
        Route::get('/contactedit/{id}', 'ImportantContactController@editcontact');
        Route::put('/updatecontact/{id}', 'ImportantContactController@updatecontact');
        Route::delete('/contactdeleteform/{id}', 'ImportantContactController@deletecontact');

        //carousel.......
        Route::get('/insertcarousel', 'CarouselController@createcarousel');
        Route::post('/storecarousel', 'CarouselController@storecarousel');
        Route::get('/viewcarousel', 'CarouselController@viewcarousel');
        Route::get('/changecarouselStatus/{id}', 'CarouselController@changeStatus');

app/Http/Controllers/Admin/IrrigationController.php
<?php

namespace App\Http\Controllers\Admin;

use App\IrrigationProject;
use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Validator;
use DB;
use File;

class IrrigationController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $data = IrrigationProject::paginate(10);
        return view('irrigation.irrigation_details')->with('irrigation', $data);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('irrigation.irrigation', ['data' => new IrrigationProject()]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {

        $data = new IrrigationProject();
        $this->setDataValue($request, $data);
        if ($request->hasFile('photo')) {
            $file = $request->file('photo');
            $destinationpath = 'uploads/irrigation';
            $uploadedImageName = uniqid() . '_' . $file->getClientOriginalName(); // unique file name with extension
            $file->move($destinationpath, $uploadedImageName);
            $data->photo = $uploadedImageName;
        }
        // dd($data);
        $data->save();
        self::Irrigationjson();

        return redirect('admin/irrigation');
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit(Request $request, $id)
    {
        $data = IrrigationProject::find($id);
        if (!$data) {
            $request->session()->flash('msg', 'Record not found !');
            return redirect('admin/irrigation');
        }
        return view('irrigation.irrigation', compact('data'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  \App\Bridge  $bridge
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $validator = Validator::make($request->all(), $this->validatedData());
        if ($validator->passes()) {
            $data = IrrigationProject::findOrFail($id);
            $this->setDataValue($request, $data);
            if ($request->hasFile('photo')) {

                $data_image = IrrigationProject::findOrFail($id);
                if ($data_image->photo && file_exists("uploads/irrigation/{$data_image->photo}")) {
                    unlink("uploads/irrigation/{$data_image->photo}");
                }
                $file =  $request->file('photo');
                $destinationpath = 'uploads/irrigation';
                $uploadedImageName = uniqid() . '_' . $file->getClientOriginalName(); // unique file name with extension
                $file->move($destinationpath, $uploadedImageName);
                $data->photo = $uploadedImageName;
            }
            // dd($data);
            $data->update();
            self::Irrigationjson();
            $request->session()->flash('msg', 'Data updated successfully !');
            return redirect('admin/irrigation');
        } else {
            return redirect('admin/irrigation/' . $id . '/edit')->withErrors($validator)->withInput();
        }
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */

     public function destroy($id, Request $request)
    {
        $del = IrrigationProject::findOrFail($id);
        if ($del->photo && file_exists("uploads/irrigation/{$del->photo}")) {
            unlink("uploads/irrigation/{$del->photo}");
        }
        $data = IrrigationProject::findOrFail($id);
        $data->delete();
        self::Irrigationjson();
        return redirect('admin/irrigation');
    }

    protected function setDataValue($request, $data)
    {
        return array(
            $data->name = $request->input('name'),
            $data->ward = $request->input('ward'),
            $data->address = $request->input('address'),
            $data->medium = $request->input('medium'),
            $data->area = $request->input('area'),
            $data->type = $request->input('type'),
            $data->beneficiary = $request->input('beneficiary'),
            $data->latitude = $request->input('latitude'),
            $data->longitude = $request->input('longitude'),
            $data->remark = $request->input('remark')
        );
    }

    protected function validatedData()
    {
        return array(
            'name' => 'required',
            'ward' => 'nullable',
            'address' => 'nullable',
            'medium' => 'nullable',
            'area' => 'nullable',
            'type' => 'nullable',
            'beneficiary' => 'nullable',
            'latitude' => 'nullable|numeric',
            'longitude' => 'nullable|numeric',
        );
    }

    public function Irrigationjson()
    {
        $irrigation = IrrigationProject::all();
        $irrigationdata = json_encode($irrigation,JSON_UNESCAPED_UNICODE);
        $file = 'irrigationdetails' . '_file.json';
        $destinationPath = public_path() . "/upload/json/";
        if (!is_dir($destinationPath)) {
            mkdir($destinationPath, 0777, true);
        }
        File::put($destinationPath . $file, $irrigationdata);
    }
}

resources/views/irrigation/irrigation.blade.php
@extends('template.admin')
@section('title', 'सिंचाई आयोजनाहरुको विवरण')
@section('page-title')
    सिंचाई आयोजनाहरुको विवरण
@endsection
@section('content')

    <div class="tab-pane" id="tab_2">
        <div class="portlet box green">
            <div class="portlet-title">
                <div class="caption">
                    <i class="fa fa-gift"></i>सिंचाई आयोजनाहरुको विवरण थप गर्नुहोस
                </div>
            </div>
            <div class="portlet-body form">
                <!-- BEGIN FORM-->
                <form method="POST"
                    action="{{ isset($data->id) ? Route('admin.irrigation.update', $data->id) : Route('admin.irrigation.store') }}"
                    enctype="multipart/form-data" class="horizontal-form">
                    @isset($data->id)
                        {{ method_field('PUT') }}
                    @endisset
                    @csrf
                    <div class="form-body">
                        {{-- <h3 class="form-section">सरकारी तथा सामुदायिक भवन</h3> --}}
                        <div class="row">
                            <div class="col-md-6">
                                {!! inputField('name', 'आयोजनको नाम', 'आयोजनको नाम', empty($data) ? old('name') : $data->name) !!}
                            </div>
                            <!--/span-->
                            <div class="col-md-6">
                                <div class="form-group">
                                    <label class="control-label">वडा नं.</label>
                                    {!! getWardCombo(0) !!}
                                </div>
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                {!! inputField('address', 'ठेगाना', 'ठेगाना', isset($data) ? $data->address : old('address')) !!}
                                @error('address') <span style="color:red;  margin-left:130px">
                                    {{ $message }} </span> @Enderror
                            </div>

                            <div class="col-md-6">
                                {!! selectField('medium', 'सिंचाइको माध्यम', [0 => 'कुलो', 'नहर', 'पाइप', isset($data) ? $data->medium : old('medium')], '') !!}
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                {!! selectField('type', 'सिंचाइको उपलब्धता', [0 => 'वर्षैभरि', 'मोसमी', isset($data) ? $data->type : old('type')], '') !!}
                            </div>
                            <div class="col-md-6">
                                {!! inputField('area', 'सिंचित क्षेत्र', 'सिंचित क्षेत्र', isset($data) ? $data->area : old('area')) !!}
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-12">
                                {!! inputField('beneficiary', 'लाभान्वित घरधुरी', 'लाभान्वित घरधुरी', isset($data) ? $data->beneficiary : old('beneficiary')) !!}
                            </div>
                        </div>

                        <div class="row">
                            <div class="col-md-6">
                                {!! latField('latitude', 'अक्षांश', 'अक्षांश', isset($data) ? $data->latitude : old('latitude')) !!}
                            </div>
                            <!--/span-->
                            <div class="col-md-6">
                                {!! latField('longitude', 'देशान्तर', 'देशान्तर', isset($data) ? $data->longitude : old('longitude')) !!}
                            </div>
                            <!--/span-->
                        </div>
                        <div class="row">
                            <div class="col-md-12">
                                <div class="form-group {{ $errors->has('remarks') ? ' has-error' : '' }} ">
                                    <label class="control-label "> कैफियत
                                    </label>
                                    <div class="col-md-12">
                                        <div class="input-icon right">
                                            <i class="fa"></i>
                                            <textarea id="editor1"
                                                name="remarks">{{ old('remarks', $data->remarks) }} </textarea>
                                            @if ($errors->has('remarks'))
                                                <span class="text-danger font-weight-danger">
                                                    {{ $errors->first('remarks') }}
                                                </span>

                                            @endif
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </div>

                    <div>
                        <button type="button" class=" btn default" href="{{ url()->previous() }}">Cancel</button>
                        <button type="submit" class="btn blue">
                            <i class="fa fa-check"></i> Save</button>
                    </div>
                </form>
                <!-- END FORM-->
            </div>
        </div>
    </div>
    <script src="https://cdn.tiny.cloud/1/blvna7bbrjyv3rg786szzwomc5wijm95tylmftaxe7yppm5o/tinymce/5/tinymce.min.js"
        referrerpolicy="origin"></script>
    <script>
        tinymce.init({
            selector: 'textarea'
        })
    </script>


@endsection

resources/views/irrigation/irrigation_details.blade.php
@extends('template.admin')
@section('title', 'सिंचाई आयोजना')
@section('page-title')
    सिंचाई आयोजनाहरुको विवरण
@endsection
@section('content')

    @if (session('status') == 'success')
        <button class="btn btn-success mt-sweetalert gk-btn-success" id="gk-success" data-title="Updated"
            data-message="Member Updated Succesfuly" data-type="success" data-allow-outside-click="true"
            data-confirm-button-class="btn-success"></button>
    @elseif (session('status') == 'delete')
        <button class="btn btn-danger mt-sweetalert gk-btn-success" id="gk-success" data-title="Delete"
            data-message="Member Deleted" data-type="error" data-allow-outside-click="true"
            data-confirm-button-class="btn-danger"></button>
    @elseif (session('status') == 'insert')
        <button class="btn btn-success mt-sweetalert gk-btn-success" id="gk-success" data-title="Inserted"
            data-message="Member Insert Succesfuly" data-type="success" data-allow-outside-click="true"
            data-confirm-button-class="btn-success"></button>
    @elseif (session('status') == 'change')
        <button class="btn btn-success mt-sweetalert gk-btn-success" id="gk-success" data-title="Updated"
            data-message="Member Status Updated" data-type="success" data-allow-outside-click="true"
            data-confirm-button-class="btn-success"></button>
    @endif

    <div class="page-bar">
        <ul class="page-breadcrumb">
            <li>
                <a href="{{ url('cd-admin/home') }}">Dashboard</a>
                <i class="fa fa-circle"></i>
            </li>

            <li>
                <span>सिंचाई आयोजनाहरुको विवरण</span>
            </li>
        </ul>
        <div class="page-toolbar">
            <div id="dashboard-report-range" class="pull-right tooltips btn btn-sm" data-container="body"
                data-placement="bottom" data-original-title="Change dashboard date range">
                <i class="icon-calendar"></i>&nbsp;
                <span class="thin uppercase hidden-xs"></span>&nbsp;
                <i class="fa fa-angle-down"></i>
            </div>
        </div>
    </div>

    <div class="row">
        <div class="col-md-12">
            <!-- BEGIN EXAMPLE TABLE PORTLET-->
            <div class="portlet light bordered">
                <div class="portlet-title">
                    <div class="caption font-dark">
                        <i class="icon-settings font-dark"></i>
                        <span class="caption-subject bold uppercase">सिंचाई आयोजनाहरुको विवरण</span>
                    </div>
                </div>
                <div class="portlet-body">
                    <div class="table-toolbar">
                        <div class="row">
                            <div class="col-md-6">
                                <div class="btn-group">
                                    <a id="sample_editable_1_new" class="btn sbold green"
                                        href="{{ route('admin.irrigation.create') }}"> Add New
                                        <i class="fa fa-plus"></i>
                                    </a>
                                </div>
                            </div>

                        </div>
                    </div>
                    <table class="table table-bordered table-striped table-condensed flip-content">
                        <thead class="flip-content">
                            <tr>
                                <th>क्र.स.</th>
                                <th>आयोजनको नाम</th>
                                <th>वडा</th>
                                <th>ठेगाना</th>
                                <th>सिंचाइको माध्यम</th>
                                <th>सिंचित क्षेत्र</th>
                                <th>सिंचाइको उपलब्धता</th>
                                <th>लाभान्वित घरधुरी</th>
                                <th>Edit</th>
                                <th>Delete</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach ($irrigation as $data)
                                <tr class="odd gradeX">
                                    {{-- {{ dd($data->name) }} --}}
                                    <td class="font-weight-bold">{{ $data->id }}</td>
                                    <td>{{ $data->name }}</td>
                                    <td>{{ $data->ward }}</td>
                                    <td>{{ $data->address }}</td>
                                    <td>{{ $data->medium }}</td>
                                    <td>{{ $data->area }}</td>
                                    <td>{{ $data->type }}</td>
                                    <td>{{ $data->beneficiary }}</td>
                                    {{-- <td>{{ $data->latitude }}</td>
                            <td>{{ $data->longitude }}</td>
                            <td>{{ $data->remarks }}</td> --}}
                                    <td>
                                        <a href="/admin/irrigation/{{ $data->id }}/edit" class="btn btn-circle green">
                                            सम्पादन गर्नुहोस्
                                            <i class="fa fa-edit"></i>
                                        </a>
                                    </td>
                                    <td><a href="#" data-toggle="modal" data-target="#{{ $data->id }}"
                                            class="btn btn-circle red"><i class="fa fa-remove"></i>मेटाउन</a>
                                        </a>
                                        <div id="{{ $data->id }}" class="modal fade" tabindex="-1"
                                            data-backdrop="static" data-keyboard="false">
                                            <div class="___class_+?38___">
                                                <div class="modal-content">
                                                    <div class="modal-header">
                                                        <button type="button" class="close" data-dismiss="modal"
                                                            aria-hidden="true"></button>
                                                        <h4 class="modal-title">पुष्टिकरण</h4>
                                                    </div>
                                                    <div class="modal-body">
                                                        <p> के तपाइँ {{ $data->name }} लाई मेटाउन चाहानुहुन्छ?
                                                        </p>
                                                    </div>
                                                    <div class="modal-footer">
                                                        <button type="button" data-dismiss="modal"
                                                            class="btn dark btn-outline">रद्द गर्नुहोस्</button>
                                                        <form class="form-sample" method="POST"
                                                            action="{{ Route('admin.irrigation.destroy', $data->id) }}">
                                                            @csrf
                                                            @method('DELETE')
                                                            <button type="submit" class="btn green">हो</button>
                                                        </form>
                                                    </div>
                                                </div>
                                            </div>
                                        </div>
                                    </td>
                                </tr>
                            @endforeach
                        </tbody>
                    </table>
                    {{ $irrigation->links() }}
                </div>
            </div>
            <!-- END EXAMPLE TABLE PORTLET-->
        </div>
    </div>
@endsection